### ISSUE TITLE
ME:Andromeda doesnt launch

### ISSUE THREAD

**Issue by Luccifer** [CadeEvs/FrostyToolsuite#72]
Got the problem, tried to disable\enable different mods, frostyFix as well, admin\non-admin launches, no luck with beta3 also

```
Input file or data stream does not conform to the expected file format specification.

   at Frosty.Core.Mod.FrostyModCollection..ctor(String fileName)
   at Frosty.ModSupport.FrostyModExecutor.Run(FileSystem inFs, CancellationToken cancelToken, ILogger inLogger, String rootPath, String modPackName, String additionalArgs, String[] modPaths)
   at FrostyModManager.MainWindow.<>c__DisplayClass13_0.<launchButton_Click>b__0(FrostyTaskWindow task)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.Core.Windows.FrostyTaskWindow.<FrostyTaskWindow_Loaded>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

![image](https://user-images.githubusercontent.com/1053009/170012040-2337cf21-d83b-43b6-94cf-ab18a804a94a.png)

**Comment by Luccifer** [comment]
Found the bug happen when trying to add mod with archve File (FBMod+Archive)

**Comment by wannkunstbeikor** [comment]
known issue, will be fixed in the next update

**Comment by wannkunstbeikor** [comment]
remove the old mods or use beta 2 to play the game

**Comment by wannkunstbeikor** [comment]
this is fixed with beta 4 https://github.com/CadeEvs/FrostyToolsuite/releases/tag/v1.0.6-beta4

**Comment by Luccifer** [comment]
Yeah, already sniped your commits, works like a charm
