### ISSUE TITLE
Frosty automatically launches my ME:A profile even when I uninstalled both FMM and ME:A

### ISSUE THREAD

**Issue by jeydowng** [CadeEvs/FrostyToolsuite#84]
I uninstalled both ME:A and FMM a while ago. When I re-downloaded FMM for DA Inquisition, it shows this error:

Z:\Steam\steamapps\common\Mass Effect Andromeda\MassEffectAndromeda.exe

   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Frosty.Core.FrostyConfiguration..ctor(String profile)
   at FrostyModManager.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I have automatically set FMM to launch my ME:A profile since last time I used it. Launching it freshly from new download opens this error however

**Comment by Bpd959** [comment]
I am also having this issue I'm trying to use frosty MM with DAI but every time I try to open frosty I get hit with the same error I don't have MEA installed and haven't in some time

**Comment by Bpd959** [comment]
Hey Jeydowng
I got it working what I did was type %appdata% in the windows taskbar menu went back and into the local folder where I found a frosty folder opened it up selected and opened the manager_config.json and changed 
"GlobalOptions": {
    "UseDefaultProfile": true,
    "DefaultProfile": "MassEffectAndromeda" 

to "GlobalOptions": {
    "UseDefaultProfile": false,
    "DefaultProfile": "MassEffectAndromeda"

**Comment by jeydowng** [comment]
Thanks man. This worked wonderfully. Cheers!
